affinidi/affinidi-core-sdk

SECURITY.md
The PR for the creation of Security.md file.
=> Security markdown creation

common-libs/common/package-lock.json, common-libs/common/package.json, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/issuer-kit/package-lock.json, sdk/issuer-kit/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json, sdk/vc-data/package-lock.json, sdk/vc-data/package.json, sdk/vc-data/src/data/medical/v1.test.ts, sdk/vc-data/src/data/medical/v1.ts
adds VC schema for the HealthPassport schema.
supports a dynamic number of bundle entries
https://replika.atlassian.net/browse/NEP-786
=> add health passport bundle vc

sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/core/src/CommonNetworkMember.ts, sdk/core/src/services/WalletStorageService.ts, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
pass options to _getCognitoUserTokensForUser
=> fix: Proper init of storageRegion in SDK constructor

common-libs/common/package-lock.json, common-libs/common/package.json, common-libs/common/src/Affinity.ts
add parse did from `did-resolver` to parse DID with params appended
=> upd validateJwt to parse did w params

common-libs/common/src/Affinity.ts, common-libs/common/src/dto/shared.dto.ts, common-libs/common/src/services/MetricsService/MetricsService.ts
https://replika.atlassian.net/browse/NEP-851
=> WIP: [NEP-851] send events for vc/vp verification failures

common-libs/common/package-lock.json, common-libs/common/package.json, common-libs/common/src/_baseDocumentLoader/index.ts, common-libs/common/src/_baseDocumentLoader/localContexts.ts, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
There were some issues where `"https://www.w3.org/2018/credentials/v1"` was not resolvable.
- Include a local copy to resolve to instead
=> feature: Setup Local Context Resolution

common-libs/common/package-lock.json, common-libs/common/package.json, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/core/src/CommonNetworkMember.ts, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
A little while back I added a warning when building a VP without an ID. But I didn't add an `id` to the VP that gets built in `CommonNetworkMember.createPresentationChallenge`.
- Add an `id` when building the VP
=> Set an id when creating a presentation from a challenge token

common-libs/common/CHANGELOG.md, common-libs/common/package-lock.json, common-libs/common/package.json, common-libs/common/src/_baseDocumentLoader/localContexts.ts, package-lock.json, package.json, sdk/browser/CHANGELOG.md, sdk/browser/README.md, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/browser/src/AffinityWallet.ts, sdk/browser/test/integration/AffinityWallet.test.ts, sdk/core/CHANGELOG.md, sdk/core/README.md, sdk/core/package-lock.json, sdk/core/package.json, sdk/core/src/CommonNetworkMember.ts, sdk/core/test/integration/NetworkMember.test.ts, sdk/expo/CHANGELOG.md, sdk/expo/README.md, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/expo/src/AffinityWallet.ts, sdk/react-native/CHANGELOG.md, sdk/react-native/README.md, sdk/react-native/package-lock.json, sdk/react-native/package.json, sdk/react-native/src/AffinityWallet.ts
Bump SDK to 4.2.0, bump common to 1.6.0
=> Setup local context resolution for "https://w3id.org/vc-revocation-list-2020/v1"

sdk/browser/CHANGELOG.md, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/CHANGELOG.md, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/CHANGELOG.md, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/issuer-kit/package-lock.json, sdk/issuer-kit/package.json, sdk/react-native/CHANGELOG.md, sdk/react-native/package-lock.json, sdk/react-native/package.json, sdk/vc-data/CHANGELOG.md, sdk/vc-data/package-lock.json, sdk/vc-data/package.json, sdk/vc-data/src/data/medical/v1.ts
Followup of https://replika.atlassian.net/browse/SAFTR-743
- Add practitioner as Bundle resource 
- Add fullUrl to bundle resource
=> Vp fhire performer

sdk/browser/CHANGELOG.md, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/CHANGELOG.md, sdk/core/package-lock.json, sdk/core/package.json, sdk/core/src/dto/shared.dto.ts, sdk/core/test/unit/CommonNetworkMember.test.ts, sdk/core/test/unit/shared/ParametersValidator.test.ts, sdk/expo/CHANGELOG.md, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/react-native/CHANGELOG.md, sdk/react-native/package-lock.json, sdk/react-native/package.json
- Fixed typo in DID regular expression which allowed "|" in DIDs (client-side)
- Added tests to reflect the change
- Updated changelog
=> [4.3.1] [FTL-1583] Fix DID regular expression used for validation

sdk/vc-data/package.json, sdk/vc-data/src/data/hackathon/index.ts, sdk/vc-data/src/data/hackathon/v1.test.ts, sdk/vc-data/src/data/hackathon/v1.ts, sdk/vc-data/src/data/index.ts
- Hackathon Winner VC
- uses schema.orh/Hackathon
- Just adds one new field awardDate
=> feat: Add Hackathon VC with awardDate

sdk/core/test/unit/services/WalletStorageService.test.ts
https://replika.atlassian.net/browse/FTL-1823
Checked and added some missing unit tests for the WalletStorageService
=> FTL-1823 add missing unit tests for WalletStorageService

sdk/vc-data/CHANGELOG.md, sdk/vc-data/package.json, sdk/vc-data/src/data/attendee/index.ts, sdk/vc-data/src/data/attendee/v1.test.ts, sdk/vc-data/src/data/attendee/v1.ts, sdk/vc-data/src/data/index.ts
- Attendee VC 
- to be issued to all attendees of webinar (2nd Sep)
=> VCAttendeePersonV1

common-libs/common/CHANGELOG.md, common-libs/common/package-lock.json, common-libs/common/package.json, common-libs/common/src/index.ts, common-libs/common/src/services/DidDocumentService/KeyVault.ts, common-libs/common/src/services/DidDocumentService/LocalKeyVault.ts, common-libs/common/src/services/DidDocumentService/index.ts, common-libs/common/src/services/index.ts, common-libs/internal-api-clients/package.json, sdk/browser/package.json, sdk/core/package.json, sdk/expo/package.json, sdk/node/package.json, sdk/react-native/package.json
Export LocalKeyVault so it can be used by other libraries.
=> Export LocalKeyVault

common-libs/internal-api-clients/package-lock.json, common-libs/internal-api-clients/package.json, common-libs/internal-api-clients/src/services/GenericApiService.ts, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
https://replika.atlassian.net/browse/FTL-1912
Mutation in GenericApiService causes bundling in some platforms to fail. Better to get rid of it.
=> FTL-1912 fix mutation in GenericApiService

common-libs/common/CHANGELOG.md, common-libs/common/package-lock.json, common-libs/common/package.json, common-libs/internal-api-clients/CHANGELOG.md, common-libs/internal-api-clients/package-lock.json, common-libs/internal-api-clients/package.json, common-libs/internal-api-clients/src/helpers/DidAuthAdapter.ts, common-libs/internal-api-clients/src/helpers/DidAuthManager.ts, common-libs/internal-api-clients/tsconfig-build.json, sdk/browser/CHANGELOG.md, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/CHANGELOG.md, sdk/core/package-lock.json, sdk/core/package.json, sdk/core/test/unit/CommonNetworkMember.test.ts, sdk/core/test/unit/services/AffinidiVaultStorageService.test.ts, sdk/expo/CHANGELOG.md, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/CHANGELOG.md, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/CHANGELOG.md, sdk/react-native/package-lock.json, sdk/react-native/package.json
Used LocalExpiringDidAuthResponseToken class from did-auth for token expiration calculation
=> LocalExpiringDidAuthResponseToken for token expiration calculation

common-libs/common/package-lock.json, common-libs/common/package.json, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
https://replika.atlassian.net/browse/FTL-2217
Fixes unpublished packages caused by NPM issue: https://status.npmjs.org/incidents/wy4002vc8ryc
=> FTL-2217 bump package versions for re-publish

sdk/core/package-lock.json, sdk/core/package.json, sdk/core/src/services/UserManagementService.ts
Some of pools request password with special character
=> Generate password with special character

common-libs/common/package-lock.json, common-libs/common/package.json, common-libs/did-auth-lib/package-lock.json, common-libs/did-auth-lib/package.json, common-libs/internal-api-clients/package-lock.json, common-libs/internal-api-clients/package.json, common-libs/tools-common/package-lock.json, common-libs/tools-common/package.json, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
Draft until https://gitlab.com/affinidi/foundational/cloud-wallet-api/-/merge_requests/159 is merged and tested on prod
=> [FTL-2364] Removed beta suffix from v6 projects (and related)

sdk/core/package-lock.json, sdk/core/package.json, sdk/core/test/integration/index.test.ts
FTL-1999. Fixed integration tests include.
=> FTL-1999. Fixed integration tests include.

sdk/browser/package-lock.json, sdk/browser/package.json, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/package-lock.json, sdk/react-native/package.json
changed: bumped version of `@affinidi/wallet-core-sdk`
=> changed: bumped version of `@affinidi/wallet-core-sdk`

common-libs/did-auth-lib/CHANGELOG.md, common-libs/did-auth-lib/README.md, common-libs/did-auth-lib/package.json, common-libs/did-auth-lib/src/DidAuthService/DidAuthService.ts
- Undepricate DidAuthService lib class in order to proceed with its usage;
- Introduce up-to-date documentation with code snippets for did-auth-lib.
=> fix(FTL-6114): updated documentation for did-auth-lib

common-libs/common/package.json, common-libs/user-management/package.json
Fixed tests for passing publish job. Follow up FTL-6523
=> fix(FTL-6523): fixed tests for passing publish job

CONTRIBUTING.md, README.md
- Moved explanation of version update utility script
=> feat(readme): moved explanation of version update utility script

common-libs/user-management/test/unit/UserManagementService.test.ts
=> fix(FTL-7741): fixed tests for publishing

common-libs/user-management/CHANGELOG.md, common-libs/user-management/package-lock.json, common-libs/user-management/package.json, common-libs/user-management/src/TrueCallerPublicKeyManager.ts, common-libs/user-management/src/TrueCallerService.ts, common-libs/user-management/test/unit/TrueCallerService.test.ts, sdk/browser/CHANGELOG.md, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/CHANGELOG.md, sdk/core/package-lock.json, sdk/core/package.json, sdk/expo/CHANGELOG.md, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/CHANGELOG.md, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/CHANGELOG.md, sdk/react-native/package-lock.json, sdk/react-native/package.json
- `TrueCallerPublicKeyManager` was added to handle fetching of Truecaller public key.
- `TrueCallerService` is updated in order to reload Truecaller public key on invalid signature verification and retry with updated key
=> feat: [FTL-8713] add add caching of TrueCaller public key

sdk/core/src/CommonNetworkMember/NetworkMemberWithCognito.ts
=> fix: remove redendant check for signin flow

sdk/core/test/integration/otp/core.test.ts
- Adds tests for getInfo(); Check for new Date()
=> feat: FTL-8240 Adds tests for getinfo()

common-libs/user-management/CHANGELOG.md, common-libs/user-management/package-lock.json, common-libs/user-management/package.json, common-libs/user-management/src/CognitoIdentityService.ts, common-libs/user-management/src/UserManagementService.ts, sdk/browser/CHANGELOG.md, sdk/browser/package-lock.json, sdk/browser/package.json, sdk/core/CHANGELOG.md, sdk/core/package-lock.json, sdk/core/package.json, sdk/core/test/integration/NetworkMember.test.ts, sdk/core/test/integration/otp/core.test.ts, sdk/core/test/integration/otp/platform.test.ts, sdk/expo/CHANGELOG.md, sdk/expo/package-lock.json, sdk/expo/package.json, sdk/node/CHANGELOG.md, sdk/node/package-lock.json, sdk/node/package.json, sdk/react-native/CHANGELOG.md, sdk/react-native/package-lock.json, sdk/react-native/package.json
https://lemmatree.atlassian.net/browse/FTL-9209
=> fix: [FTL-9209] fix error
